language: node_js
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    node_js: '4'
    env: DEPLOY_TARGET=hockey DEPLOY_IOS=true DEPLOY_ANDROID=false
  - os: linux
    node_js: '4'
    env: DEPLOY_TARGET=hockey DEPLOY_IOS=false DEPLOY_ANDROID=true
  - os: osx
    osx_image: xcode7.3
    node_js: '4'
    env: DEPLOY_TARGET=testflight DEPLOY_IOS=true DEPLOY_ANDROID=false
  - os: linux
    node_js: '4'
    env: DEPLOY_TARGET=playstore DEPLOY_IOS=false DEPLOY_ANDROID=true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- openssl aes-256-cbc -K $encrypted_af3788150926_key -iv $encrypted_af3788150926_iv
  -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp .keystore ~/.keystore
install:
# ruby
- rvm install 2.2.5
- rvm use 2.2.5

# fastlane
- if [ $DEPLOY_IOS == "true" ]; then gem install fastlane --no-ri --no-rdoc; fi

# meteor
- curl https://install.meteor.com | /bin/sh
- export PATH=$PATH:$HOME/.meteor

# npm
- npm install

# launch
- npm install -g meteor-launch

# android
- if [ $DEPLOY_ANDROID == "true" ]; then wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz; fi
- if [ $DEPLOY_ANDROID == "true" ]; then tar zxvf android-sdk_r24.4.1-linux.tgz > /dev/null; fi
- if [ $DEPLOY_ANDROID == "true" ]; then mv android-sdk-linux .android; fi
- if [ $DEPLOY_ANDROID == "true" ]; then export ANDROID_HOME="$TRAVIS_BUILD_DIR/.android"; fi
- if [ $DEPLOY_ANDROID == "true" ]; then echo y | .android/tools/android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-23; fi
- if [ $DEPLOY_ANDROID == "true" ]; then export ANDROID_ZIPALIGN="$TRAVIS_BUILD_DIR/.android/build-tools/23.0.3/zipalign"; fi
- if [ $DEPLOY_ANDROID == "true" ]; then sudo apt-get install lib32z1 libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5; fi

# remove platforms if possible
- if [ $DEPLOY_IOS == "false" ]; then meteor remove-platform ios; fi
- if [ $DEPLOY_ANDROID == "false" ]; then meteor remove-platform android; fi

script:
- launch build launch-todos-example.herokuapp.com settings.json
- if [ $DEPLOY_TARGET == "hockey" ]; then launch hockey; fi
- if [ $DEPLOY_TARGET == "testflight" ]; then launch testflight; fi
- if [ $DEPLOY_TARGET == "playstore" ] ; then launch playstore; fi
deploy:
  provider: heroku
  api_key:
    secure: Dd0klkm+/XI3bWYQ0EU8xLwlXApwYp+icOxG3Xdy9IFnZcNhh9nms+V+nd+aMmfziNLNOYcXHK1tpJMQZ7gXyeZWj5G96oWOBNtB+/lLzEGEC7AONzoV/iLRo9txNeeuOB0Q1v3/Jg4I4V7pCbTeoFc0s9rHyUHJ4t/FiZBpLXnJItbO4zlXJdMbSAdRycnSYay3XOckcyJ9fpmFUH6Tu3S9kv6RT61+0mWoT5QuS/ME+Ur5wNuR8SVSMeD21BykUFNOGg+5Hwukaz9MfoDZ6Jzii2MpJdgK6xYH1PVwdNEotSm9vJYt09HfnkIqHoVuClpZnY1WmAAaFjuIixY21J5D5TbVahqFbS35eHgMP/kXS/sPhNDegrYIfyEFeSf14c8Ut6oM6kkBVUue7Byx17jo2qQT2g1Z1ldFD2o9nvFYwGXW9UMnOVwxlahYQm1VvNfHwrJzVPCII2OOc2noANTPlB9efc1XPt+IL7pEZhWl+2Ltg5j1WLAFFScaF2AFCl/v78LM1fHJJXOK/V9436ZaGx5nhSw/QbfYY/YhD4j5E4xxslaUV+WE5PXd2+00tRyZM2AbJntoXcBM6gClH/qowc3BpNrk8TJxEnXkl7Gr/zvICFhtjFpVfaBm9pNAVsQ9wXVACoQ6+O4zpeGP68vbg1dZRjZA7V73LN+e7Gk=
  app: launch-todos-example
  on:
    repo: NewSpring/launch-todos-example
