os:
- osx
osx_image: xcode7.3
language: node_js
node_js:
- '4'
env:
- DEPLOY_TARGET=hockey DEPLOY_IOS=true DEPLOY_ANDROID=true
- DEPLOY_TARGET=testflight DEPLOY_IOS=true DEPLOY_ANDROID=false
- DEPLOY_TARGET=playstore DEPLOY_IOS=false DEPLOY_ANDROID=true
before_install:
- openssl aes-256-cbc -K $encrypted_af3788150926_key -iv $encrypted_af3788150926_iv
  -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp .keystore ~/.keystore
install:
# ruby
- rvm install 2.2.5
- rvm use 2.2.5

# fastlane
- if [ $DEPLOY_IOS == "true" ]; then gem install fastlane --no-ri --no-rdoc; fi

# meteor
- curl https://install.meteor.com | /bin/sh

# npm
- npm install

# launch
- npm install -g newspring/meteor-launch#update

# android
- if [ $DEPLOY_ANDROID == "true" ]; then brew install android-sdk; fi
- if [ $DEPLOY_ANDROID == "true" ]; then export ANDROID_HOME=/usr/local/opt/android-sdk; fi
- if [ $DEPLOY_ANDROID == "true" ]; then echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-23; fi
- if [ $DEPLOY_ANDROID == "true" ]; then export ANDROID_ZIPALIGN=/usr/local/opt/android-sdk/build-tools/23.0.3/zipalign; fi

# remove platforms if possible
- if [ $DEPLOY_IOS == "false" ]; then meteor remove-platform ios; fi
- if [ $DEPLOY_ANDROID == "false" ]; then meteor remove-platform android; fi
script:
- launch build launch-todos-example.meteor.com
- if [ $DEPLOY_TARGET == "hockey" ]; then launch hockey; fi
- if [ $DEPLOY_TARGET == "testflight" ]; then launch testflight; fi
- if [ $DEPLOY_TARGET == "playstore" ] ; then launch playstore; fi
