os:
- osx
osx_image: xcode7.3
language: node_js
node_js:
- '4'
cache:
  directories:
  - "$HOME/.rvm"
  - "$HOME/.meteor"
before_install:
- openssl aes-256-cbc -K $encrypted_af3788150926_key -iv $encrypted_af3788150926_iv
  -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- rvm install 2.2.5
- rvm use 2.2.5
script:
- curl https://install.meteor.com | /bin/sh
- gem install fastlane --no-ri --no-rdoc
- npm install -g newspring/meteor-launch#update
- launch build launch-todos-example.meteor.com
- launch hockey
