os:
- osx
osx_image: xcode7.3
language: node_js
node_js:
- '4'
before_install:
- rvm install 2.2.5
- rvm use 2.2.5
script:
- gem install fastlane --no-ri --no-rdoc
- npm install -g newspring/meteor-launch#update
- launch test
