os:
- osx
osx_image: xcode7.3
language: node_js
node_js:
- '4'
cache:
  directories:
  - "$HOME/.rvm"
  - "$HOME/.meteor"
  - "$HOME/.nvm"
before_install:
- openssl aes-256-cbc -K $encrypted_af3788150926_key -iv $encrypted_af3788150926_iv
  -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
# ruby
- rvm install 2.2.5
- rvm use 2.2.5

# fastlane
- gem install fastlane --no-ri --no-rdoc

# meteor
- if [ ! -d ~/.meteor ]; then curl https://install.meteor.com | /bin/sh; fi

# npm
- npm install

# launch
- npm install -g newspring/meteor-launch#update

# android
- brew install android-sdk
- export ANDROID_HOME=/usr/local/opt/android-sdk
- echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-23
- export ANDROID_ZIPALIGN=/usr/local/opt/android-sdk/build-tools/23.0.3/zipalign
script:
- launch build launch-todos-example.meteor.com
- launch hockey
